### ISSUE TITLE
Keine Darstellung von Tabellen in readme.md 

### ISSUE THREAD

**Issue by Nall-chan** [lociii/symcon-index#1]
Tabellen werden nicht dargestellt.
Beispiel:
https://symcon-index.herokuapp.com/library/5603d208-76a4-4359-b546-cc450cab6984

**Comment by lociii** [comment]
Das Parsen der Readme erfolgt ueber python-markdown (http://pythonhosted.org/Markdown/).
Schaue ich mir gerne an, ob die Bibliothek das ueberhaupt kann.

Danke.
